### ISSUE TITLE
Release of the pretrained model

### ISSUE THREAD

**Issue by Liampour** [Anonymous1563/Bayesian-Enhancement-Model#1]
Hello,

Congratulation for your amazing work!! Based on the paper and preview seems very promising!!
Have you set a date for releasing the pre-trained model?

I can't wait to try it

Thank you very much!

**Comment by BinCVER** [comment]
Thank you for your interest in our work.

The pre-trained models will be released within a week.

If you found our repository useful, please consider giving it a star, as it means a lot to us. Thank you!

**Comment by Liampour** [comment]
Thank you for the information, your time and contribution!!
