### ISSUE TITLE
Inference code for Bayesian Enhancement Model

### ISSUE THREAD

**Issue by MK-1307** [Anonymous1563/Bayesian-Enhancement-Model#3]
Hi there,

I gone through the repo of **Bayesian Enhancement Model** , Its quite interesting, can i have the inference code to test on real data.

**Comment by BinCVER** [comment]
Hi, thank you for your interest in our work!

To test your own data, you can use the eval.py file. Start by specifying a no-reference metric, such as NIQE, using the `--no_ref niqe` argument. Then, set the input directory with the `--input_dir` argument.

Here’s an example of how to run the inference:

```
python3 Enhancement/eval.py --opt experiments/CG_UNet_LOLv2Real/CG_UNet_LOLv2Real.yml \
--weights experiments/CG_UNet_LOLv2Real/ckpt.pth \
--cond_opt experiments/IE_UNet_LOLv2Real/IE_UNet_LOLv2Real.yml \
--cond_weights experiments/IE_UNet_LOLv2Real/ckpt.pth \
--num_samples 100 \
--no_ref niqe \
--input_dir dir2urdata
```

**Comment by zhangjy328** [comment]
Where can I get the output results?Can the output path be specified?
