### ISSUE TITLE
关于UIEB数据集

### ISSUE THREAD

**Issue by caojiale555** [Anonymous1563/Bayesian-Enhancement-Model#6]
你好，请问UIEB数据集是怎样划分的

**Comment by caojiale555** [comment]
你是怎么划分训练集，测试集 的 input和 gt

**Comment by BinCVER** [comment]
You can download the UIEB dataset, which is already divided into three subsets (training, R90, and C60), from [this link](https://github.com/Anonymous1563/Bayesian-Enhancement-Model/releases/tag/checkpoints_%26_visual_results).

If our work is helpful to you, please consider giving our repo a star. 😊
